package me.vertex.core.mine;

import me.vertex.core.booster.BoosterCategory;
import me.vertex.core.booster.BoosterService;
import me.vertex.core.lang.Messages;
import me.vertex.core.backpack.BackpackAutoStoreListener;
import org.bukkit.Location;
import org.bukkit.Color;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;
import org.bukkit.entity.Monster;
import org.bukkit.event.entity.CreatureSpawnEvent;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.EntityEquipment;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.LeatherArmorMeta;

import java.util.concurrent.ThreadLocalRandom;

/**
 * Everything that happens inside a mining region.
 *
 * <p>Placing blocks is denied, so nothing inside a region can be
 * player-placed. That is what makes "is this ore plugin-generated?" a
 * question with a free answer: anything in the region was generated by the
 * mine, and none of the usual fake-ore exploits (placing your own, hauling
 * blocks in, place/break farming) are reachable in the first place.
 */
public final class MineListener implements Listener {

    private final MineManager mines;
    private final BoosterService boosters;
    private final Messages messages;
    private final BackpackAutoStoreListener backpackDrops;

    public MineListener(MineManager mines, BoosterService boosters, Messages messages,
            BackpackAutoStoreListener backpackDrops) {
        this.mines = mines;
        this.boosters = boosters;
        this.messages = messages;
        this.backpackDrops = backpackDrops;
    }

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onBloodveinMobSpawn(CreatureSpawnEvent event) {
        if (!(event.getEntity() instanceof Monster monster)) return;
        MineRegion region = mines.regionAt(monster.getLocation());
        if (region == null || !region.id().equalsIgnoreCase("bloodvein")) return;
        EntityEquipment equipment = monster.getEquipment();
        if (equipment == null) return;
        Color[] colors = {Color.fromRGB(45, 20, 70), Color.fromRGB(75, 25, 100),
                Color.fromRGB(35, 35, 35), Color.fromRGB(110, 20, 35), Color.fromRGB(20, 65, 80)};
        Color color = colors[ThreadLocalRandom.current().nextInt(colors.length)];
        equipment.setHelmet(leather(Material.LEATHER_HELMET, color));
        equipment.setChestplate(leather(Material.LEATHER_CHESTPLATE, color));
        equipment.setLeggings(leather(Material.LEATHER_LEGGINGS, color));
        equipment.setBoots(leather(Material.LEATHER_BOOTS, color));
        equipment.setHelmetDropChance(0F);
        equipment.setChestplateDropChance(0F);
        equipment.setLeggingsDropChance(0F);
        equipment.setBootsDropChance(0F);
    }

    private static ItemStack leather(Material material, Color color) {
        ItemStack item = new ItemStack(material);
        LeatherArmorMeta meta = (LeatherArmorMeta) item.getItemMeta();
        meta.setColor(color);
        item.setItemMeta(meta);
        return item;
    }

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onPlace(BlockPlaceEvent event) {
        if (!mines.denyBlockPlace() || mines.regionAt(event.getBlock().getLocation()) == null) {
            return;
        }
        event.setCancelled(true);
        event.getPlayer().sendMessage(messages.get(event.getPlayer(), "mines.cannot-place"));
    }

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onBreak(BlockBreakEvent event) {
        Block block = event.getBlock();
        MineRegion region = mines.regionAt(block.getLocation());
        if (region == null) {
            return;
        }
        Player player = event.getPlayer();

        if (!region.isMineBlock(block.getType())) {
            // Structure, walls, floor, decoration -- anything the mine does
            // not generate is not the player's to break.
            if (mines.denyNonMineBreak()) {
                event.setCancelled(true);
                player.sendMessage(messages.get(player, "mines.cannot-break"));
            }
            return;
        }

        // Vertex owns the drop entirely: Silk Touch cannot yield the ore
        // block itself, and Fortune has no effect. Only the configured base
        // drop and the Ore Drop booster decide the amount.
        event.setDropItems(false);
        event.setExpToDrop(0);

        if (!region.isOre(block.getType())) {
            // A base block still regenerates, it just pays nothing.
            mines.scheduleRegen(region, block);
            return;
        }

        MineOreTable.Entry entry = region.oreEntry(block.getType());
        int amount = applyOreBooster(player, entry.dropAmount());
        if (amount > 0) {
            java.util.List<ItemStack> drops = java.util.List.of(new ItemStack(entry.dropMaterial(), amount));
            ItemStack offhandBefore = player.getInventory().getItemInOffHand().clone();
            java.util.List<ItemStack> leftovers = backpackDrops == null
                    ? drops : backpackDrops.routePlayerMiningDrops(player, drops);
            if (!mines.queueOverflow(player, leftovers, "mine-ore")) {
                player.getInventory().setItemInOffHand(offhandBefore);
                player.updateInventory();
                event.setCancelled(true);
                player.sendMessage(messages.get(player, "delivery.storage-unavailable"));
                return;
            }
        }
        mines.scheduleRegen(region, block);
    }

    /** Blaze-rod corner selection, mirroring the KOTH wand. */
    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = false)
    public void onWand(PlayerInteractEvent event) {
        if (event.getHand() != EquipmentSlot.HAND || !mines.isSelectionWand(event.getItem())) {
            return;
        }
        Player player = event.getPlayer();
        switch (event.getAction()) {
            case LEFT_CLICK_BLOCK -> {
                event.setCancelled(true);
                mines.setCorner(player, blockLocation(event), true);
            }
            case RIGHT_CLICK_BLOCK -> {
                event.setCancelled(true);
                mines.setCorner(player, blockLocation(event), false);
            }
            case LEFT_CLICK_AIR, RIGHT_CLICK_AIR -> {
                if (player.isSneaking()) {
                    event.setCancelled(true);
                    mines.completeSelection(player);
                }
            }
            default -> {
                // Physical interactions are not selection actions.
            }
        }
    }

    private static Location blockLocation(PlayerInteractEvent event) {
        return event.getClickedBlock().getLocation();
    }

    /**
     * Applies the combined Ore Drop bonus.
     *
     * <p>Above 100% the bonus becomes guaranteed extra drops plus a chance at
     * one more, so a +150% booster is always at least 2.5x and averages
     * exactly that rather than silently rounding away the fraction.
     */
    private int applyOreBooster(Player player, int baseAmount) {
        double percent = boosters == null ? 0D : boosters.effectivePercent(player, BoosterCategory.ORE_DROP);
        if (percent <= 0D) {
            return baseAmount;
        }
        double bonus = baseAmount * percent / 100D;
        int guaranteed = (int) Math.floor(bonus);
        double fraction = bonus - guaranteed;
        int extra = guaranteed + (fraction > 0D && ThreadLocalRandom.current().nextDouble() < fraction ? 1 : 0);
        return baseAmount + extra;
    }

}
